// <auto-generated />
using System;
using KuyumcuPrivate.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KuyumcuPrivate.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260412152419_SplitGoldCoinsCumhuriyetResat")]
    partial class SplitGoldCoinsCumhuriyetResat
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KuyumcuPrivate.Domain.Entities.AssetType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("GramWeight")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int?>("Karat")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("UnitType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("AssetTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Code = "TRY",
                            IsActive = true,
                            Name = "Türk Lirası",
                            SortOrder = 1,
                            UnitType = "Currency"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            Code = "USD",
                            IsActive = true,
                            Name = "Dolar",
                            SortOrder = 2,
                            UnitType = "Currency"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            Code = "EUR",
                            IsActive = true,
                            Name = "Euro",
                            SortOrder = 3,
                            UnitType = "Currency"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            Code = "GBP",
                            IsActive = true,
                            Name = "Sterlin",
                            SortOrder = 4,
                            UnitType = "Currency"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000014"),
                            Code = "SAR",
                            IsActive = true,
                            Name = "Suudi Riyali",
                            SortOrder = 5,
                            UnitType = "Currency"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            Code = "GOLD22",
                            GramWeight = 1.0000m,
                            IsActive = true,
                            Karat = 22,
                            Name = "22 Ayar Altın",
                            SortOrder = 6,
                            UnitType = "Gram"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            Code = "GOLD24",
                            GramWeight = 1.0000m,
                            IsActive = true,
                            Karat = 24,
                            Name = "24 Ayar Altın",
                            SortOrder = 7,
                            UnitType = "Gram"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            Code = "C_CEYREK",
                            GramWeight = 1.7540m,
                            IsActive = true,
                            Karat = 22,
                            Name = "Cumhuriyet Çeyrek",
                            SortOrder = 8,
                            UnitType = "Piece"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000008"),
                            Code = "C_YARIM",
                            GramWeight = 3.5080m,
                            IsActive = true,
                            Karat = 22,
                            Name = "Cumhuriyet Yarım",
                            SortOrder = 9,
                            UnitType = "Piece"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000009"),
                            Code = "C_TAM",
                            GramWeight = 7.0160m,
                            IsActive = true,
                            Karat = 22,
                            Name = "Cumhuriyet Tam",
                            SortOrder = 10,
                            UnitType = "Piece"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000011"),
                            Code = "C_GREMSE",
                            GramWeight = 17.5400m,
                            IsActive = true,
                            Karat = 22,
                            Name = "Cumhuriyet Gremse",
                            SortOrder = 11,
                            UnitType = "Piece"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000012"),
                            Code = "C_BESLI",
                            GramWeight = 35.0800m,
                            IsActive = true,
                            Karat = 22,
                            Name = "Cumhuriyet Beşli",
                            SortOrder = 12,
                            UnitType = "Piece"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000015"),
                            Code = "R_CEYREK",
                            GramWeight = 1.8040m,
                            IsActive = true,
                            Karat = 22,
                            Name = "Reşat Çeyrek",
                            SortOrder = 13,
                            UnitType = "Piece"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000016"),
                            Code = "R_YARIM",
                            GramWeight = 3.6080m,
                            IsActive = true,
                            Karat = 22,
                            Name = "Reşat Yarım",
                            SortOrder = 14,
                            UnitType = "Piece"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000010"),
                            Code = "R_TAM",
                            GramWeight = 7.2160m,
                            IsActive = true,
                            Karat = 22,
                            Name = "Reşat Tam",
                            SortOrder = 15,
                            UnitType = "Piece"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000017"),
                            Code = "R_GREMSE",
                            GramWeight = 18.0400m,
                            IsActive = true,
                            Karat = 22,
                            Name = "Reşat Gremse",
                            SortOrder = 16,
                            UnitType = "Piece"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000018"),
                            Code = "R_BESLI",
                            GramWeight = 36.0800m,
                            IsActive = true,
                            Karat = 22,
                            Name = "Reşat Beşli",
                            SortOrder = 17,
                            UnitType = "Piece"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000013"),
                            Code = "SILVER",
                            GramWeight = 1.0000m,
                            IsActive = true,
                            Name = "Gümüş",
                            SortOrder = 18,
                            UnitType = "Gram"
                        });
                });

            modelBuilder.Entity("KuyumcuPrivate.Domain.Entities.Balance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<Guid>("AssetTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AssetTypeId");

                    b.HasIndex("CustomerId", "AssetTypeId")
                        .IsUnique();

                    b.ToTable("Balances");
                });

            modelBuilder.Entity("KuyumcuPrivate.Domain.Entities.Conversion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("FromAmount")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<Guid>("FromAssetId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("FromRateTry")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<string>("RateNote")
                        .HasColumnType("text");

                    b.Property<string>("RateSource")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ToAmount")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<Guid>("ToAssetId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ToRateTry")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TryEquivalent")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.HasKey("Id");

                    b.HasIndex("FromAssetId");

                    b.HasIndex("ToAssetId");

                    b.HasIndex("TransactionId")
                        .IsUnique();

                    b.ToTable("Conversions");
                });

            modelBuilder.Entity("KuyumcuPrivate.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NationalId")
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("bytea");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("KuyumcuPrivate.Domain.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Amount")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<Guid?>("AssetTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("CancelReason")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("boolean");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AssetTypeId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("CustomerId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("KuyumcuPrivate.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            FullName = "Sistem Yöneticisi",
                            IsActive = true,
                            PasswordHash = "$2a$11$Hlu3yqAS8.BJeHGwZmW06eSSS7dZnaVQNyHwgbN.AbW9G0ly4waj2",
                            Role = "Admin",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("KuyumcuPrivate.Domain.Entities.Balance", b =>
                {
                    b.HasOne("KuyumcuPrivate.Domain.Entities.AssetType", "AssetType")
                        .WithMany("Balances")
                        .HasForeignKey("AssetTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KuyumcuPrivate.Domain.Entities.Customer", "Customer")
                        .WithMany("Balances")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssetType");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("KuyumcuPrivate.Domain.Entities.Conversion", b =>
                {
                    b.HasOne("KuyumcuPrivate.Domain.Entities.AssetType", "FromAsset")
                        .WithMany()
                        .HasForeignKey("FromAssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KuyumcuPrivate.Domain.Entities.AssetType", "ToAsset")
                        .WithMany()
                        .HasForeignKey("ToAssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KuyumcuPrivate.Domain.Entities.Transaction", "Transaction")
                        .WithOne("Conversion")
                        .HasForeignKey("KuyumcuPrivate.Domain.Entities.Conversion", "TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FromAsset");

                    b.Navigation("ToAsset");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("KuyumcuPrivate.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("KuyumcuPrivate.Domain.Entities.AssetType", "AssetType")
                        .WithMany("Transactions")
                        .HasForeignKey("AssetTypeId");

                    b.HasOne("KuyumcuPrivate.Domain.Entities.User", "CreatedByUser")
                        .WithMany("Transactions")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KuyumcuPrivate.Domain.Entities.Customer", "Customer")
                        .WithMany("Transactions")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssetType");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("KuyumcuPrivate.Domain.Entities.AssetType", b =>
                {
                    b.Navigation("Balances");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("KuyumcuPrivate.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Balances");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("KuyumcuPrivate.Domain.Entities.Transaction", b =>
                {
                    b.Navigation("Conversion");
                });

            modelBuilder.Entity("KuyumcuPrivate.Domain.Entities.User", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
